using Maki.Api.Configuration;
using Maki.Data;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;

namespace Maki.Api.Services;

/// <summary>
/// Rebuilds everything Maki keeps as an image on disk: the reader's page thumbnails under
/// <c>cache/reader</c>, the source-comparison samples under <c>cache/sourcepreview</c>, and the
/// series posters under <c>MediaCover</c>.
/// <para>
/// The two cache folders are only ever deleted — a thumbnail is regenerated by the next reader
/// request that wants it, so recreating them eagerly would decode the whole library to produce
/// images nobody has asked for. Posters are the opposite: nothing regenerates one on demand, so a
/// missing poster stays missing until something re-downloads it, which is what this does.
/// </para>
/// <para>
/// Long-running and single-flighted through <see cref="ImageCacheRebuildStatus"/>. Runs from
/// <c>ImageCacheRebuildJob</c> so it lives on Quartz's shutdown path rather than dying with the
/// request that started it.
/// </para>
/// </summary>
public class ImageCacheRebuildService(
    MakiDbContext db,
    AppPaths paths,
    CoverService covers,
    SeriesMetadataRefreshService metadataRefresh,
    ImageCacheRebuildStatus status,
    ILogger<ImageCacheRebuildService> logger)
{
    /// <param name="force">
    /// True re-downloads every poster; false only touches series whose poster is missing or does not
    /// decode.
    /// </param>
    /// <returns>false when a rebuild is already in flight, so this call did nothing.</returns>
    public async Task<bool> RunAsync(bool force, CancellationToken ct)
    {
        // The claim is taken here rather than in the endpoint: a status left saying "running" by a
        // trigger that never reached a job would need a restart to clear.
        if (!status.TryBegin(force))
        {
            return false;
        }

        string? error = null;
        try
        {
            status.SetPhase("clearing");
            var cleared = ClearCacheDir(paths.ReaderCacheDir) + ClearCacheDir(paths.SourcePreviewDir)
                + ClearCacheDir(paths.SeriesPreviewDir);
            status.ReportThumbnailsCleared(cleared);

            DeleteOrphanedCoverDirs(ct);

            if (!ct.IsCancellationRequested)
            {
                await RebuildCoversAsync(force, ct);
            }
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            // Shutdown mid-pass. Everything here is idempotent, so the next manual run picks up
            // whatever this one did not reach.
            logger.LogInformation("Image cache rebuild cancelled by shutdown");
        }
        catch (Exception ex)
        {
            error = ex.Message;
            logger.LogWarning(ex, "Image cache rebuild failed");
        }
        finally
        {
            status.End(error);
            status.InvalidateUsage();
            // Every poster in the library was identified or decoded, so the pool is as full as it
            // gets, and nothing else needs it until the next decode. Same reason as HealthScanService.
            SixLabors.ImageSharp.Configuration.Default.MemoryAllocator.ReleaseRetainedResources();
        }

        return true;
    }

    /// <summary>
    /// What the caches hold right now. Memoized in the status singleton because it walks the whole
    /// thumbnail folder and decodes every poster header, and the settings card polls.
    /// </summary>
    public async Task<ImageCacheUsage> UsageAsync(CancellationToken ct)
    {
        if (status.CachedUsage() is { } cached)
        {
            return cached;
        }

        var (coverFiles, coverBytes) = MeasureDir(paths.MediaCoverDir);
        var (thumbFiles, thumbBytes) = MeasureDir(paths.ReaderCacheDir);

        var ids = await db.Series.IgnoreQueryFilters().Select(s => s.Id).ToListAsync(ct);
        var missing = ids.Count(id => !IsUsableCover(covers.CoverPathFor(id)));

        var usage = new ImageCacheUsage(
            coverFiles, coverBytes, thumbFiles, thumbBytes, ids.Count, missing);
        status.CacheUsage(usage);
        return usage;
    }

    private static (int Files, long Bytes) MeasureDir(string root)
    {
        if (!Directory.Exists(root))
        {
            return (0, 0);
        }

        var files = 0;
        long bytes = 0;
        foreach (var file in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
        {
            try
            {
                bytes += new FileInfo(file).Length;
                files++;
            }
            catch (IOException)
            {
                // Deleted between the enumeration and the stat, e.g. by a rebuild running now.
            }
        }

        return (files, bytes);
    }

    /// <summary>
    /// Empties one cache folder, one entry at a time. A single recursive delete would abandon the
    /// rest of the folder the moment one file is locked, and on Windows a thumbnail being streamed
    /// to a reader right now is exactly that.
    /// </summary>
    /// <returns>How many files were actually removed.</returns>
    private int ClearCacheDir(string root)
    {
        if (!Directory.Exists(root))
        {
            return 0;
        }

        var removed = 0;
        foreach (var file in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
        {
            try
            {
                File.Delete(file);
                removed++;
            }
            catch (Exception ex)
            {
                logger.LogDebug(ex, "Could not delete cached image {File}", file);
            }
        }

        foreach (var dir in Directory.GetDirectories(root))
        {
            try
            {
                Directory.Delete(dir, recursive: true);
            }
            catch (Exception ex)
            {
                logger.LogDebug(ex, "Could not delete cache dir {Dir}", dir);
            }
        }

        return removed;
    }

    /// <summary>
    /// Drops poster folders for series that no longer exist. Same hazard <see cref="CoverService"/>
    /// guards on delete: the folder is named by series id, SQLite reuses rowids, and
    /// <c>MediaCoverController</c> resolves a cover by id alone — so a leftover folder eventually
    /// serves a deleted series' art under a new series' name.
    /// <para>
    /// Reads the id set with <c>IgnoreQueryFilters</c>. The scope this runs under is unrestricted,
    /// but a filtered read here would treat every series the caller cannot see as deleted and wipe
    /// its poster.
    /// </para>
    /// </summary>
    private void DeleteOrphanedCoverDirs(CancellationToken ct)
    {
        if (!Directory.Exists(paths.MediaCoverDir))
        {
            return;
        }

        var live = db.Series.IgnoreQueryFilters().Select(s => s.Id).ToHashSet();
        foreach (var dir in Directory.GetDirectories(paths.MediaCoverDir))
        {
            if (ct.IsCancellationRequested)
            {
                return;
            }

            if (int.TryParse(Path.GetFileName(dir), out var id) && live.Contains(id))
            {
                continue;
            }

            try
            {
                Directory.Delete(dir, recursive: true);
            }
            catch (Exception ex)
            {
                logger.LogDebug(ex, "Could not delete orphaned cover dir {Dir}", dir);
            }
        }
    }

    private async Task RebuildCoversAsync(bool force, CancellationToken ct)
    {
        status.SetPhase("covers");

        // IgnoreQueryFilters for the same reason as above: this is instance maintenance, and the
        // set of series it covers must not depend on whose scope the job happens to run under.
        var all = await db.Series.IgnoreQueryFilters().Include(s => s.RootFolder).ToListAsync(ct);
        var targets = force ? all : all.Where(s => !IsUsableCover(covers.CoverPathFor(s.Id))).ToList();
        status.SetTotal(targets.Count);

        var cancelled = false;
        foreach (var series in targets)
        {
            if (ct.IsCancellationRequested)
            {
                cancelled = true;
                break;
            }

            if (series.MangaBakaId is null)
            {
                // Nowhere to fetch from. Not a failure: a manually added series with no provider
                // match never had a poster to rebuild.
                status.ReportCover(downloaded: false, failed: false, skipped: true);
                continue;
            }

            try
            {
                var ok = await metadataRefresh.RefreshCoverAsync(series, ct);
                status.ReportCover(downloaded: ok, failed: !ok, skipped: false);
            }
            catch (OperationCanceledException) when (ct.IsCancellationRequested)
            {
                cancelled = true;
                break;
            }
            catch (Exception ex)
            {
                logger.LogWarning(ex, "Cover rebuild failed for {Title}", series.Title);
                status.ReportCover(downloaded: false, failed: true, skipped: false);
            }
        }

        // Whatever did land is worth keeping, so a cancelled pass saves too — on its own token,
        // since ct is the one that just fired.
        await db.SaveChangesAsync(cancelled ? CancellationToken.None : ct);
    }

    /// <summary>
    /// Whether a poster on disk is worth keeping. A zero-byte or truncated file is the usual
    /// leftover of a download that died halfway, and it looks identical to a good one to
    /// <c>File.Exists</c>, so the header is decoded rather than trusted.
    /// </summary>
    internal static bool IsUsableCover(string path)
    {
        try
        {
            var info = new FileInfo(path);
            if (!info.Exists || info.Length == 0)
            {
                return false;
            }

            Image.Identify(path);
            return true;
        }
        catch
        {
            return false;
        }
    }
}
